### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-3-evaluacion-intermedia-bellita85#1]
Buen trabajo @bellita85 !

### Algunas pistas para acabarlo:

- [x] Pon un `<label>` para indicar para qué es cada `<input>` y recuerda asociarlos con el atributo `htmlFor`.
- [x] Hace falta una variable estado para cada `input` que usamos en el formulario de una nueva adalaber.
- [x] Haz que los `input` del formulario sean "componentes controlados": deben tener una función handler en su evento `onChange` y una variable de estado en su atributo `value`.
- [x] Resetea el estado de tu formulario cuando agregues una adalabers(limpia los inputs)
- [x] Verifica si hay valores en los inputs antes de añadir una nueva frase a la lista.
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)
- [x] Elimina el código comentado, debuggers y consoles: https://github.com/Adalab/modulo-3-evaluacion-intermedia-bellita85/blob/fbdbbf6457998d617e94f273418dcd7c5395213e/src/components/App.js#L123 
- [x] Haz los bonus del ejercicio para que sigas practicando! 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by bellita85** [comment]
todo ok
